version: "3.8"
services:
  fastapi:
    build: .
    command: uvicorn app.server:app --host 0.0.0.0 --port 8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    environment:
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
